// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacationService.Infrastructure.Persistence;

#nullable disable

namespace ARCA.Vacation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("VacationService.Domain.Entities.VacationBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManagementYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsedDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "ManagementYear")
                        .IsUnique();

                    b.ToTable("VacationBalances");
                });
#pragma warning restore 612, 618
        }
    }
}
